" Plugins ---{{{
" " PlugUpdate
call plug#begin('~/.vim/plugged')
Plug 'christoomey/vim-tmux-navigator'
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'thoughtbot/vim-rspec'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'slim-template/vim-slim'
Plug 'vifm/vifm'
Plug 'vim-ruby/vim-ruby'
Plug 'Raimondi/delimitMate'
Plug 'dense-analysis/ale'
Plug 'jiangmiao/auto-pairs'
Plug 'godlygeek/tabular'
Plug 'github/copilot.vim'
Plug 'tomasr/molokai'
Plug 'itchyny/lightline.vim'
call plug#end()

let g:rspec_command = "Dispatch bundle exec rspec -I . {spec}"

" How can I open a NERDTree automatically when vim starts up if no files were
" specified?
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" }}}

" Basic settings ---{{{
" Leader
let mapleader = " "
let maplocalleader = " "

" strip trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Use Vim settings, rather than Vi settings (much better!).
" " This must be first, because it changes other options as a side effect.
set nocompatible
set tabstop=4
set softtabstop=2
set shiftwidth=4
set expandtab
set incsearch " Enable incremental search
set hlsearch " Enable highlight search
set termwinsize=12x0 " Set terminal size
set splitbelow " Always split below
set mouse=a
set number

" Write swp files to /tmp instead of current directory
set swapfile
set dir=/tmp

" Make it obvious where 100 characters is
" highlight ColorColumn ctermbg=18
set textwidth=100

" lightline
set noshowmode

" Ale (Linting)
let b:ale_fixers = {'ruby': ['standardrb'], 'rust': ['rustfmt']}
let g:ale_fix_on_save = 1
let g:ale_sign_error = '>>'

" Open fzf
noremap <Leader>p :Files<CR>

nmap <Leader>n :NERDTreeToggle<CR>

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" Colorscheme
syntax enable
colorscheme molokai

hi LineNr          ctermfg=250 ctermbg=234

"" Font
set guifont=Monaco

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-p>"
    endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>
" }}}

" Silver Searcher ---{{{
" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in fzf for listing files. Lightning fast and respects .gitignore
  let $FZF_DEFAULT_COMMAND = 'ag --literal --files-with-matches --nocolor --hidden -g ""'

  if !exists(":Ag")
    command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
    nnoremap \ :Ag<SPACE>
  endif
endif

" NERDTree
let NERDTreeShowBookmarks = 1   " Show the bookmarks table
let NERDTreeShowHidden = 1      " Show hidden files
let NERDTreeShowLineNumbers = 0 " Hide line numbers
let NERDTreeMinimalMenu = 1     " Use the minimal menu (m)
let NERDTreeWinPos = "left"     " Panel opens on the left side
let NERDTreeWinSize = 31        " Set panel width to 31 columns

" Ruby
" Set the Ruby filetype for a number of common Ruby files without .rb
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,Procfile,Guardfile,config.ru,*.rake} set ft=ruby
